### PR TITLE
2-01-authentication-service

### LINKED ISSUE #26: FOXFLOW-2-01: Authentication Service
### Issue FOXFLOW-2-01: 

- [x] Configure OAuth [Firebase Authentication](https://firebase.google.com/docs/auth).
> (one or both options)
  - [x] Login with Email & Password
  - [x] Google
  - [x] GitHub

- [x] Integrate the login & Registration page with a chosen authentication service (Firebase) to handle user authentication.
- [x] Implement error handling for failed authentication and display user-friendly error messages.

#### Template: 

- Use Angular CLI to generate a new component for the `login` page.
- Use Angular CLI to generate a new component for the `signup` page.
- The Header is visible on the pages.

- Add a friendly welcome test:
  - Example: "You’re one click away from less busywork"
  - Example: "Welcome to Asana. To get started, please sign in"

- Create login form (email, password)
- Create Login Button on the `login` page (one or both options):
  - Add `google-auth-button`: Link to the authorization with the Google account.
  - Add `github-auth-button`: Link to the authorization with the GitHub account.

- Create Signup form (user name, email, password)
- Create Signup Button on the `signup` page (one or both options):
  - Add `google-auth-button`: Link to the authorization with the Google account.
  - Add `github-auth-button`: Link to the authorization with the GitHub account.

#### Functionality:

- Handle user authentication.
- Error handling for failed authentication.

#### Visual Implementation Ideas:

- Consider using descriptive labels for the links to help users understand where each link will take them. 
  - For instance, "Continue with Google" for the login page and "Continue with your Google work account" for the registration page. 
  - Or "Sign in with GitHub".
- Add the Google / GitHub icon to the button.

#### Styling:

- Use SCSS or [Angular Material](https://material.angular.dev/components/categories) to style the UI elements for a clean and modern look.
- Ensure proper spacing and alignment of elements.

#### Responsiveness:

- Implement a responsive design that works well on both desktop and mobile.
- Optimize images and assets: Ensure images are responsive and load efficiently on all devices.

> Note: Responsive layout (BreakpointObserver or modern CSS) - 15 pts

#### Accessibility:

- Implement ARIA roles and attributes: Use ARIA roles to enhance screen reader compatibility for navigation and task elements.
- Ensure keyboard navigation: Make sure all interactive elements are accessible via keyboard (e.g., tab navigation).
- Use color contrast guidelines: Ensure text and background colors meet WCAG contrast ratio standards for readability.
- Provide alt text for images: Include descriptive alt text for all images to assist visually impaired users.
- [Angular Material Tooltip](https://material.angular.dev/components/tooltip/overview)

#### Feature catalog: 
5) Architecture & Components – up to 90 pts
   - [ ] Feature-sliced structure (core/shared/ui/features) - 30 pts
   - [ ] Reusable components with clear inputs/outputs, content projection - 20 pts
   - [x] Useful attribute or structural directives - 20 pts
   - [ ] DI patterns: injection tokens for config, clean boundaries - 10 pts
   - [ ] Well-designed pure pipes with strong typing - 10 pts

7) Forms (Reactive Forms) – up to 80 pts
   - [x] Complex form with custom validators (sync + async), clear error UX - 40 pts
   - [ ] Dynamic fields with FormArray - 15 pts
   - [ ] Save draft and restore form state - 15 pts
   - [x] Keyboard access, labels, aria-describedby for errors - 10 pts

### LINKED ISSUE #27: FOXFLOW-2-02: Redirection
## Redirection.

- [ ] FOXFLOW-2-02: Redirection.

Redirect users to the application's `home` page upon successful login, allowing them to access the main features and content of the application. The `home` page can contain simple text (e.g., "Home") or any other content to demonstrate that the user is successfully logged in. Ensure that the URL in the address bar is changed to the main page's URL, properly handling navigation and user experience during redirection.

#### URL Change and Redirection Tasks:

- Implement a function or module in your application that redirects users from the login page to the `home` page.
- Update the URL in the address bar to reflect the correct URL for the `home` page (e.g., "/home") upon successful redirection.
- Ensure that the browser's navigation (history) is updated correctly when redirecting users to the main page, allowing them to use the back button to navigate to the previous page if necessary.

#### Redirection and Authentication State Checking Tasks:

- Implement a function, service, or route guard in your application that checks whether a user is already authenticated when a user attempts to visit the login page.
- Make sure that the user's authentication state is preserved during the redirection process, allowing them to stay logged in when accessing the `home`  page.
- If the user is authenticated, redirect them to the `home` page, preventing access to the login page while they are logged in.
- Ensure that the browser's navigation (history) is updated correctly when redirecting authenticated users to the `home` page.

> Note: Guards/resolvers with typed data - 20 pts

### PR DESCRIPTION
**Pull request by IevgeniiaAbdulina**
1. Task: [RS Clone – Angular Final Project](https://github.com/rolling-scopes-school/tasks/blob/master/angular/modules/rsclone/README.md)
2. Screenshot:
login-page
register-page

3. Deploy: [FoxFlow Task Management app](https://foxflowangular2025.web.app/)
5. Done: 2025-09-14 / Deadline: 2025-10-06

## The feature list:

- [x] Configure Firebase OAuth.
- [x] Login & Registration with Email & Password.
- [x] OAuth with Google.
- [x] OAuth with GitHub.
- [x] Login & Registration page.
- [x] Complex Form with custom validators.
- [x] Implement error handling.
- [x] Handle user authentication.
- [x] URL Change and Redirection after signing in the user.
- [x] Redirection and Authentication State.
- [x] AuthGuard & IsLoggedGuard.

Points: 90 / 600

### 2) Routing & Navigation – up to 20/110 pts

- [x] Guards/resolvers with typed data - 20 pts

### 5) Architecture & Components – up to 20/90 pts

- [x] Useful attribute or structural directives - 20 pts

### 6) Forms (Reactive Forms) – up to 50/80 pts

- [x] Complex form with custom validators (sync + async), clear error UX - 40 pts
- [x] Keyboard access, labels, aria-describedby for errors - 10 pts

### CODE REVIEW

**Review by rekunolya — APPROVED** [review]
Looks good

**Review by InaFK — APPROVED** [review]
Thank you!
Login & registration work as expected.

File: src/app/app.ts [hunk 1]
```diff
@@ -3,38 +3,36 @@ import {
...
-  protected readonly testConnection = signal('');
-
-  firebaseService = inject(FirebaseServiceTs);
+  authService = inject(AuthService);
 
   ngOnInit(): void {
-    this.firebaseService.getTestConnection().subscribe((documents) => {
-      const firstDoc = documents[0];
-      this.testConnection.set(firstDoc?.['text'] ?? '');
+    this.authService.user$.subscribe((user) => {
```
Comment (ALIAKSEI-sl) [inline src/app/app.ts]: It would be better to unsubscribe here, but it's not necessary.

File: src/app/app.ts [hunk 2]
```diff
@@ -3,38 +3,36 @@ import {
...
+        this.authService.currentUser.set({
+          uid: user.uid,
+          email: user.email!,
+          displayName: user.displayName!,
+          photoURL: user.photoURL!,
+        });
+      } else {
+        this.authService.currentUser.set(null);
+      }
+      console.log(this.authService.currentUser());
```
Comment (ALIAKSEI-sl) [inline src/app/app.ts]: Are you sure, it's need?

File: src/app/auth/components/login/login.html [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+      role="form"
+      [formGroup]="form"
+      (ngSubmit)="onSubmit()">
+      <mat-form-field
+        appearance="outline"
+        aria-labelledby="personalInfo"
+        class="login-form__full-width"
+        role="group">
+        <mat-label>{{ 'LOGIN_PAGE.LABEL_EMAIL' | translate }}</mat-label>
+        <input
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/login/login.html:63]: A lots different attributes, but where is name?

File: src/app/auth/components/login/login.ts [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+  fb = inject(FormBuilder);
+  router = inject(Router);
+  authService = inject(AuthService);
+  private destroyRef = inject(DestroyRef);
+  notificationService = inject(NotificationService);
+
+  readonly errorMessage = signal<string | null>(null);
+  readonly hide = signal<boolean>(true);
+
+  form = this.fb.nonNullable.group({
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/login/login.ts:67]: It would be better to do it in OnInit.

File: src/app/auth/components/login/login.ts [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+    email: ['', [Validators.required, Validators.email]],
+    password: ['', Validators.required],
+  });
+
+  visibilityToggle(event: MouseEvent): void {
+    this.hide.set(!this.hide());
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/login/login.ts]: It would be better to use update.

File: src/app/auth/components/login/login.ts [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+    event.stopPropagation();
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/login/login.ts:74]: Is it necessary here?

File: src/app/auth/components/login/login.html [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+      </mat-form-field>
+
+      @if (form.get("password")?.hasError("required") &&
+      form.get("password")?.touched) {
+      <mat-error>
+        {{ "LOGIN_PAGE.ERROR_MESSAGE.REQUIRED" | translate }}
+      </mat-error>
+      } @if (errorMessage()) {
+      <mat-error>{{ errorMessage() }}</mat-error>
+      }
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/login/login.html:115]: Isthere any sense in this error message? I guess this just duplicates existing messages.

File: src/app/auth/components/register/register.html [hunk 8]
```diff
@@ -0,0 +1,167 @@
...
+            ? colorValid
+            : colorError">
+          {{ 'REGISTER_PAGE.ERROR_MESSAGE.SPECIAL_CHAR' | translate }}
+        </mat-error>
+        <mat-error
+          [appHighlightMessage]="controlValidity('.{8,}')
+            ? colorValid
+            : colorError">
+          {{ 'REGISTER_PAGE.ERROR_MESSAGE.CHARS_LONG' | translate }}
+        </mat-error>
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.html:173]: Duplicate code. Could you create a custom validator?

File: src/app/auth/components/register/register.html [hunk 9]
```diff
@@ -0,0 +1,167 @@
...
+        }
+      </div>
+      } @if (errorMessage()) {
+      <mat-error>{{ errorMessage() }}</mat-error>
+      }
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.html:178]: the same thing

File: src/app/auth/components/register/register.ts [hunk 10]
```diff
@@ -0,0 +1,142 @@
...
+  authService = inject(AuthService);
+  private destroyRef = inject(DestroyRef);
+  notificationService = inject(NotificationService);
+
+  readonly errorMessage = signal<string | null>(null);
+  colorError = '#ba1a1a';
+  colorValid = '#00c853';
+  readonly hide = signal<boolean>(true);
+
+  form = this.fb.nonNullable.group({
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.ts:74]: the same thing

File: src/app/auth/components/register/register.ts [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+    username: [
+      '',
+      [Validators.required, Validators.minLength(3), this.noSpecialChars],
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.ts]: Validator have to be function, not a method.

File: src/app/auth/components/register/register.ts [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+    password: [
+      '',
+      [Validators.required, Validators.pattern(StrongPasswordRegx)],
+    ],
+  });
+
+  visibilityToggle(event: MouseEvent): void {
+    this.hide.set(!this.hide());
+    event.stopPropagation();
+  }
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.ts]: the same thing

File: src/app/auth/components/register/register.html [hunk 13]
```diff
@@ -0,0 +1,167 @@
...
+        </mat-label>
+        <input
+          formControlName="username"
+          matInput
+          placeholder="{{ 'REGISTER_PAGE.LABEL_USERNAME' | translate }}"
+          type="text" />
+      </mat-form-field>
+
+      @if (form.get("username")?.invalid && form.get("username")?.touched) {
+      <mat-error>{{ getErrorMessage("username") }}</mat-error>
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.html]: It's better avoid calling method in template, in login better way.

File: src/app/auth/components/register/register.html [hunk 14]
```diff
@@ -0,0 +1,167 @@
...
+        <mat-label>{{ 'REGISTER_PAGE.LABEL_EMAIL' | translate }}</mat-label>
+        <input
+          formControlName="email"
+          matInput
+          placeholder="{{ 'REGISTER_PAGE.LABEL_EMAIL' | translate }}"
+          type="email" />
+      </mat-form-field>
+
+      @if (form.get("email")?.invalid && form.get("email")?.touched) {
+      <mat-error>{{ getErrorMessage("email") }}</mat-error>
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.html]: the same thing

File: src/app/auth/components/register/register.html [hunk 15]
```diff
@@ -0,0 +1,167 @@
...
+          (click)="visibilityToggle($event)">
+          <mat-icon matSuffix>
+            {{ hide() ? 'visibility_off' : 'visibility' }}
+          </mat-icon>
+        </button>
+      </mat-form-field>
+
+      @if (form.get("password")?.invalid) { @if (form.get("password")?.touched)
+      {
+      <mat-error>{{ getErrorMessage("password") }}</mat-error>
```
Comment (ALIAKSEI-sl) [inline src/app/auth/components/register/register.html]: the same thing

File: src/app/auth/services/auth-service.ts [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+@Injectable({
+  providedIn: 'root',
+})
+export class AuthService {
+  firebaseAuth = inject(Auth);
+  router = inject(Router);
+  notificationService = inject(NotificationService);
+
+  user$: Observable<User | null> = user(this.firebaseAuth);
+  readonly currentUser = signal<UserInterface | null | undefined>(undefined);
```
Comment (ALIAKSEI-sl) [inline src/app/auth/services/auth-service.ts]: Null or undefined?

File: src/app/auth/services/auth-service.ts [hunk 17]
```diff
@@ -0,0 +1,101 @@
...
+  }
+
+  login(email: string, password: string): Observable<void> {
+    const promise = signInWithEmailAndPassword(
+      this.firebaseAuth,
+      email,
+      password
+    ).then(() => {
+      /* empty */
+    });
```
Comment (ALIAKSEI-sl) [inline src/app/auth/services/auth-service.ts:52]: you can just remove then.

File: src/app/app.routes.ts [hunk 18]
```diff
@@ -1,3 +1,35 @@
...
+  },
+  {
+    path: 'register',
+    component: Register,
+    canActivate: [isLoggedGuard],
+  },
+  {
+    path: 'main',
+    component: MainPage,
+    canActivate: [isLoggedGuard],
```
Comment (ALIAKSEI-sl) [inline src/app/app.routes.ts]: Can't logined user visit this page?

File: src/app/features/components/home-page/home-page.ts [hunk 19]
```diff
@@ -0,0 +1,13 @@
...
+import { AsyncPipe, NgOptimizedImage } from '@angular/common';
+
+@Component({
+  selector: 'app-home-page',
+  imports: [AsyncPipe, NgOptimizedImage],
+  templateUrl: './home-page.html',
+  styleUrl: './home-page.scss',
+})
+export class HomePage {
+  authService = inject(AuthService);
```
Comment (ALIAKSEI-sl) [inline src/app/features/components/home-page/home-page.ts]: Service must be private. And you can use signal as well.

File: src/app/shared/components/snack-bar-notification/snack-bar-notification.ts [hunk 20]
```diff
@@ -0,0 +1,35 @@
...
+    MatSnackBarActions,
+    MatSnackBarAction,
+    NgClass,
+  ],
+  templateUrl: './snack-bar-notification.html',
+  styleUrl: './snack-bar-notification.scss',
+})
+export class SnackBarNotification {
+  snackBarRef = inject(MatSnackBarRef);
+  data: SnackBarData = inject(MAT_SNACK_BAR_DATA);
```
Comment (ALIAKSEI-sl) [inline src/app/shared/components/snack-bar-notification/snack-bar-notification.ts]: services must be private.

File: src/app/shared/components/social-button-github/social-button-github.ts [hunk 21]
```diff
@@ -0,0 +1,13 @@
...
+import { MatIconModule } from '@angular/material/icon';
+
+@Component({
+  selector: 'app-social-button-github',
+  imports: [MatButtonModule, MatIconModule],
+  templateUrl: './social-button-github.html',
+  styleUrl: './social-button-github.scss',
+})
+export class SocialButtonGithub {
+  readonly loginWithGitHub = output();
```
Comment (ALIAKSEI-sl) [inline src/app/shared/components/social-button-github/social-button-github.ts:12]: void

File: src/app/shared/components/social-button-google/social-button-google.ts [hunk 22]
```diff
@@ -0,0 +1,14 @@
...
+
+@Component({
+  selector: 'app-social-button-google',
+  imports: [MatButtonModule, MatIconModule],
+  templateUrl: './social-button-google.html',
+  styleUrl: './social-button-google.scss',
+  changeDetection: ChangeDetectionStrategy.OnPush,
+})
+export class SocialButtonGoogle {
+  readonly loginWithGoogle = output();
```
Comment (ALIAKSEI-sl) [inline src/app/shared/components/social-button-google/social-button-google.ts:13]: the same thing

File: src/app/shared/directives/highlight-message.ts [hunk 23]
```diff
@@ -0,0 +1,14 @@
...
+@Directive({
+  selector: '[appHighlightMessage]',
+})
+export class HighlightMessage implements OnChanges {
+  readonly appHighlightMessage = input.required<string>();
+
+  private el = inject(ElementRef);
+
+  ngOnChanges(): void {
+    this.el.nativeElement.style.color = this.appHighlightMessage();
```
Comment (ALIAKSEI-sl) [inline src/app/shared/directives/highlight-message.ts:20]: Could you use Renderer2 here?

File: src/app/shared/services/notification-service.ts [hunk 24]
```diff
@@ -0,0 +1,35 @@
...
+
+@Injectable({
+  providedIn: 'root',
+})
+export class NotificationService {
+  private _snackBar = inject(MatSnackBar);
+
+  horizontalPosition: MatSnackBarHorizontalPosition = 'right';
+  verticalPosition: MatSnackBarVerticalPosition = 'top';
+  durationInSeconds = 10;
```
Comment (ALIAKSEI-sl) [inline src/app/shared/services/notification-service.ts]: private?

**Review by ALIAKSEI-sl — APPROVED** [review]

File: src/app/app.ts (hunk 2 above)
Comment (IevgeniiaAbdulina) [reply src/app/app.ts:35]: `.pipe(takeUntilDestroyed(this.destroyRef))`

Comment (IevgeniiaAbdulina) [reply src/app/app.ts]: Removed

File: src/app/app.ts (hunk 1 above)
Comment (IevgeniiaAbdulina) [reply src/app/app.ts]: `.pipe(takeUntilDestroyed(this.destroyRef))`

File: src/app/auth/components/login/login.ts (hunk 4 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/login/login.ts:67]: While it is not necessary to create a `FormGroup` in the `ngOnInit` method when using `FormBuilder`, it can be beneficial for more complex forms or when additional setup is required. Because our form is simple, initializing it directly in the property declaration is perfectly acceptable.

File: src/app/auth/components/login/login.ts (hunk 5 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/login/login.ts]: Used `this.hide.update()`

File: src/app/auth/components/login/login.ts (hunk 6 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/login/login.ts:74]: This part of the code was added from the Angular Material documentation as an example of how to use clickable elements inside the input field.
By calling `event.stopPropagation(`) in the `clickEvent` function, I prevent the click event from bubbling up to parent elements. This ensures that only the intended action (toggling the password visibility) occurs without triggering any unintended behaviors in parent components.

File: src/app/shared/services/notification-service.ts (hunk 24 above)
Comment (IevgeniiaAbdulina) [reply src/app/shared/services/notification-service.ts]: added `private`

File: src/app/features/components/home-page/home-page.ts (hunk 19 above)
Comment (IevgeniiaAbdulina) [reply src/app/features/components/home-page/home-page.ts]: added `private`

File: src/app/auth/components/login/login.html (hunk 7 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/login/login.html:115]: This error message doesn't duplicate other messages. It occurs when the form is invalid, but other error messages are from the server response.

File: src/app/auth/components/login/login.html (hunk 3 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/login/login.html:63]: added attribute `name` for all input fields.

File: src/app/auth/components/register/register.ts (hunk 10 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.ts:74]: While it is not necessary to create a `FormGroup` in the `ngOnInit` method when using `FormBuilder`, it can be beneficial for more complex forms or when additional setup is required. Because our form is simple, initializing it directly in the property declaration is perfectly acceptable.

File: src/app/auth/components/register/register.ts (hunk 12 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.ts]: Added ` this.hide.update((value) => !value);`

File: src/app/auth/components/register/register.html (hunk 15 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.html]: These error Messages are from built-in errors. But the messages below are from custom usage.

File: src/app/auth/components/register/register.html (hunk 9 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.html:178]: This works in such a way that messages are not confused with each other.

File: src/app/auth/components/register/register.ts (hunk 11 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.ts]: Done

File: src/app/app.routes.ts (hunk 18 above)
Comment (IevgeniiaAbdulina) [reply src/app/app.routes.ts]: Yes, this page can only be seen by unauthorized users.

File: src/app/auth/components/register/register.html (hunk 13 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.html]: removed methods from template

File: src/app/auth/components/register/register.html (hunk 14 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/components/register/register.html]: remove method call from template

File: src/app/shared/directives/highlight-message.ts (hunk 23 above)
Comment (IevgeniiaAbdulina) [reply src/app/shared/directives/highlight-message.ts:20]: done

File: src/app/auth/services/auth-service.ts (hunk 16 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/services/auth-service.ts]: removed unnecessary `undefined`

File: src/app/auth/services/auth-service.ts (hunk 17 above)
Comment (IevgeniiaAbdulina) [reply src/app/auth/services/auth-service.ts:52]: In this case, ESLint has an error: ESLint: Unexpected empty arrow function. So, I need to put something inside.
